---
- name: Ensure apt cache is up to date
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install REP backend packages
  ansible.builtin.apt:
    name: "{{ rep_core_packages | default(['nginx', 'python3-venv']) }}"
    state: present

- name: Enable nginx service
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: Create REP configuration directory
  ansible.builtin.file:
    path: /opt/rep/config
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
