---
- name: Ensure CTI sharing service directory exists
  ansible.builtin.file:
    path: "{{ cti_ss_taxii_config | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Configure TAXII collections
  ansible.builtin.template:
    src: taxii.yaml.j2
    dest: "{{ cti_ss_taxii_config }}"
    owner: root
    group: root
    mode: "0640"
  notify: restart cti sharing service
  no_log: true

- name: Validate CTI sharing daemon configuration
  ansible.builtin.command: "cti-ssctl configtest --config {{ cti_ss_taxii_config }}"
  register: cti_ss_configtest
  changed_when: false
  failed_when: cti_ss_configtest.rc != 0

- name: Check CTI sharing service status
  ansible.builtin.command: "{{ cti_ss_healthcheck_command }}"
  register: cti_ss_status
  changed_when: false
  failed_when: cti_ss_status.rc != 0 or 'running' not in cti_ss_status.stdout.lower()
