---
- name: Configure Corp Router
  hosts: corp_router
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install iptables packages
      apt:
        name:
          - iptables
          - iptables-persistent
        state: present

    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Configure NAT masquerading on all interfaces
      command: iptables -t nat -A POSTROUTING -o {{ item }} -j MASQUERADE
      loop: "{{ ansible_interfaces }}"
      when: item != 'lo'
      notify: save iptables rules

    - name: Ensure netfilter-persistent service enabled
      systemd:
        name: netfilter-persistent
        enabled: yes
        state: started

  handlers:
    - name: save iptables rules
      command: iptables-save > /etc/iptables/rules.v4

