---
- name: Verify SOC Services
  hosts: soc_server
  become: yes
  tasks:
    - name: Check Elasticsearch service status
      command: systemctl is-active elasticsearch
      register: elastic_status
      changed_when: false
      failed_when: elastic_status.stdout.strip() != "active"

    - name: Check TheHive service status
      command: systemctl is-active thehive
      register: thehive_status
      changed_when: false
      failed_when: thehive_status.stdout.strip() != "active"

    - name: Check MISP service status
      command: systemctl is-active apache2
      register: misp_status
      changed_when: false
      failed_when: misp_status.stdout.strip() != "active"
