---
trainee_workstation_collector:
  service_name: REPCollector
  config_path: C:\\ProgramData\\REP\\collector.yaml
  log_path: C:\\ProgramData\\REP\\collector.log
  directory: C:\\ProgramData\\REP
  ingestion_pipeline:
    interval_minutes: 1
    transports:
      - type: https
        url: https://rep-core.internal/ingest
        token: changeme
      - type: syslog
        host: soc-gateway.internal
        port: 514
trainee_workstation_shortcuts:
  - path: C:\\Users\\Public\\Desktop\\LiveSession.url
    url: https://rep-core.internal/live
    icon: C:\\Program Files\\Internet Explorer\\iexplore.exe
trainee_workstation_health_command: "Get-Service -Name REPCollector"
trainee_workstation_welcome_note:
  directory: C:\\Labs
  filename: WELCOME.txt
  content: |
    Welcome to the Random Education Platform lab environment.
    Follow your instructor's guidance to complete the phishing awareness exercises.
