name: Molecule

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - provisioning/subcase-1a
          - provisioning/subcase-1d
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Molecule dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-plugins[docker] docker

      - name: Execute Molecule tests
        working-directory: ${{ matrix.scenario }}
        run: molecule test
